name: Github pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types:
      - rebuild-site

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm ci
    - name: Install docusaurus
      run: npm install -g docusaurus
    - name: Rebuild github page
      run: npm run build
    - name: Deploy webpage
      run: npm run deploy
